### ISSUE TITLE
EUP-UI Errors

### ISSUE THREAD

**Issue by DarkLifeStudio** [Zaps6000/eup-ui#1]
Hi, i have a little problem when i try to open the menu it does'nt open and when i check in my F8 consol i see this
![image](https://github.com/Zaps6000/eup-ui/assets/128855570/da515300-db17-4f50-b3a0-7ba6fc7996a2)

**Comment by ScrachStack** [comment]
Error with the json file.

**Comment by ScrachStack** [comment]
fixed v3
